export const RISK_GATE_V2_MODULES = [
  "geopolitical_security",
  "geoeconomic_trade",
  "political_governance",
  "sovereign_fiscal",
  "macro_monetary",
  "currency_capital_mobility",
  "banking_financial_system",
  "payments_treasury",
  "supply_chain_logistics",
  "energy_commodities",
  "regulatory_legal",
  "infrastructure_cyber_technology",
  "climate_environment_hazard",
  "societal_labor_health",
  "information_influence",
  "emerging_long_tail",
] as const;

export type RiskGateV2Module =
  (typeof RISK_GATE_V2_MODULES)[number];

export const RISK_GATE_V2_SUBJECT_TYPES = [
  "country",
  "corridor",
  "region",
  "subnational",
  "city",
  "port",
  "airport",
  "border_crossing",
  "chokepoint",
  "logistics_route",
  "energy_route",
  "currency_pair",
  "commodity",
  "market",
  "sector",
  "counterparty_exposure",
  "portfolio_exposure",
  "event",
  "custom_basket",
] as const;

export type RiskGateV2SubjectType =
  (typeof RISK_GATE_V2_SUBJECT_TYPES)[number];

export const RISK_GATE_V2_ACTION_TYPES = [
  "cross_border_payment",
  "treasury_transfer",
  "cash_concentration",
  "fx_conversion",
  "fx_hedge",
  "settlement",
  "lending_credit_exposure",
  "trade_finance",
  "counterparty_review",
  "investment_allocation_review",
  "supply_chain_sourcing",
  "shipment_route_planning",
  "commodity_procurement",
  "insurance_underwriting_review",
  "institutional_wallet_transfer",
  "stablecoin_transfer",
  "stablecoin_redemption",
  "autonomous_financial_agent_action",
  "custom",
] as const;

export type RiskGateV2ActionType =
  (typeof RISK_GATE_V2_ACTION_TYPES)[number];

export const RISK_GATE_V2_COVERAGE_STATES = [
  "FULL",
  "PARTIAL",
  "LIMITED",
  "INSUFFICIENT",
] as const;

export type RiskGateV2CoverageState =
  (typeof RISK_GATE_V2_COVERAGE_STATES)[number];

export const RISK_GATE_V2_DISPLAY_LABELS = [
  "CLEAR",
  "CAUTION",
  "REVIEW",
  "HOLD",
] as const;

export type RiskGateV2DisplayLabel =
  (typeof RISK_GATE_V2_DISPLAY_LABELS)[number];

export const RISK_GATE_V2_DRIVER_CATALOG = {
  geopolitical_security: [
    "interstate_conflict",
    "civil_conflict",
    "military_escalation",
    "territorial_dispute",
    "terrorism_political_violence",
    "coup_unconstitutional_transfer",
    "election_instability",
    "protest_civil_unrest",
    "diplomatic_rupture",
    "alliance_change",
    "border_closure",
    "military_mobilization",
    "expropriation_nationalization",
  ],
  geoeconomic_trade: [
    "sanctions",
    "secondary_sanctions_exposure",
    "asset_freezes",
    "export_controls",
    "import_restrictions",
    "tariffs",
    "quotas",
    "embargoes",
    "investment_screening",
    "trade_retaliation",
    "forced_localization",
    "technology_restrictions",
    "forced_labor_supply_chain_restrictions",
    "payment_system_exclusion",
  ],
  political_governance: [
    "government_stability",
    "policy_continuity",
    "rule_of_law_deterioration",
    "institutional_weakness",
    "governance_deterioration",
    "regulatory_unpredictability",
    "civic_instability",
    "emergency_state_intervention",
  ],
  sovereign_fiscal: [
    "sovereign_credit_deterioration",
    "debt_sustainability",
    "default_restructuring_risk",
    "fiscal_deficit_stress",
    "public_finance_deterioration",
    "reserve_adequacy",
    "external_funding_dependence",
    "debt_service_burden",
  ],
  macro_monetary: [
    "growth_slowdown_recession",
    "inflation",
    "interest_rate_shock",
    "monetary_policy_divergence",
    "labor_market_stress",
    "current_account_stress",
    "balance_of_payments_stress",
    "liquidity_conditions",
    "demand_shock",
  ],
  currency_capital_mobility: [
    "currency_shock",
    "fx_volatility",
    "reserve_depletion",
    "capital_controls",
    "convertibility_restrictions",
    "repatriation_restrictions",
    "multiple_exchange_rate_regimes",
    "offshore_onshore_market_dislocation",
  ],
  banking_financial_system: [
    "banking_system_stress",
    "funding_stress",
    "deposit_flight",
    "credit_deterioration",
    "sovereign_bank_feedback",
    "market_liquidity_stress",
    "capital_market_closure",
    "financial_contagion",
    "settlement_system_stress",
  ],
  payments_treasury: [
    "cross_border_payment_disruption",
    "correspondent_banking_constraints",
    "payment_rail_outage",
    "settlement_delay",
    "beneficiary_jurisdiction_restrictions",
    "digital_asset_rail_restriction",
    "settlement_reserve_redemption_risk",
    "banking_holiday_emergency_closure",
    "treasury_repatriation_constraints",
  ],
  supply_chain_logistics: [
    "port_disruption",
    "maritime_security",
    "shipping_lane_disruption",
    "border_congestion_closure",
    "customs_disruption",
    "airfreight_disruption",
    "rail_road_disruption",
    "supplier_concentration",
    "critical_component_shortage",
    "inventory_shock",
    "freight_cost_shock",
    "insurance_withdrawal_war_risk_premium",
  ],
  energy_commodities: [
    "oil_gas_disruption",
    "electricity_grid_disruption",
    "food_agriculture_shock",
    "metals_shock",
    "rare_earth_disruption",
    "critical_mineral_disruption",
    "fertilizer_petrochemical_disruption",
    "strategic_commodity_dependency",
    "energy_transit_chokepoint_exposure",
  ],
  regulatory_legal: [
    "regulatory_change",
    "licensing_restriction",
    "tax_capital_treatment_change",
    "foreign_investment_restriction",
    "data_localization_requirement",
    "contract_enforcement_deterioration",
    "legal_system_disruption",
    "product_sector_ban",
  ],
  infrastructure_cyber_technology: [
    "critical_infrastructure_disruption",
    "cyberattack_systemic_impact",
    "telecom_outage",
    "internet_shutdown",
    "cloud_datacenter_regional_disruption",
    "satellite_gnss_disruption",
    "submarine_cable_disruption",
    "semiconductor_technology_supply_shock",
    "export_controlled_technology_dependency",
  ],
  climate_environment_hazard: [
    "extreme_weather",
    "flood",
    "drought",
    "wildfire",
    "earthquake",
    "storm_cyclone",
    "water_stress",
    "heat_stress",
    "climate_policy_shock",
    "physical_asset_logistics_interruption",
  ],
  societal_labor_health: [
    "strike_labor_disruption",
    "migration_shock",
    "social_instability",
    "public_health_emergency",
    "workforce_availability_shock",
    "social_fragility_transmission",
  ],
  information_influence: [
    "misinformation_disinformation_shock",
    "information_integrity_deterioration",
    "foreign_interference",
    "market_moving_false_information",
    "communications_restriction",
  ],
  emerging_long_tail: [
    "rare_material_shortage",
    "unusual_capital_control",
    "insurance_market_withdrawal",
    "emergency_shipping_restriction",
    "navigation_interference",
    "critical_cable_outage",
    "sudden_digital_asset_restriction",
    "unexpected_reserve_rule",
    "rapid_nationalization_measure",
    "new_war_risk_zone",
    "sanctions_enforcement_shock",
  ],
} as const satisfies Record<
  RiskGateV2Module,
  readonly string[]
>;

export type RiskGateV2Driver = {
  [Module in RiskGateV2Module]:
    (typeof RISK_GATE_V2_DRIVER_CATALOG)[Module][number];
}[RiskGateV2Module];

export const RISK_GATE_V2_DEFAULT_ACTION_MODULES: Partial<
  Record<RiskGateV2ActionType, readonly RiskGateV2Module[]>
> = {
  cross_border_payment: [
    "geopolitical_security",
    "geoeconomic_trade",
    "sovereign_fiscal",
    "macro_monetary",
    "currency_capital_mobility",
    "banking_financial_system",
    "payments_treasury",
  ],
  treasury_transfer: [
    "geopolitical_security",
    "geoeconomic_trade",
    "sovereign_fiscal",
    "macro_monetary",
    "currency_capital_mobility",
    "banking_financial_system",
    "payments_treasury",
  ],
  fx_conversion: [
    "macro_monetary",
    "currency_capital_mobility",
    "banking_financial_system",
    "geopolitical_security",
    "geoeconomic_trade",
  ],
  fx_hedge: [
    "macro_monetary",
    "currency_capital_mobility",
    "banking_financial_system",
    "geopolitical_security",
    "geoeconomic_trade",
  ],
  lending_credit_exposure: [
    "political_governance",
    "sovereign_fiscal",
    "macro_monetary",
    "currency_capital_mobility",
    "banking_financial_system",
    "regulatory_legal",
  ],
  supply_chain_sourcing: [
    "geopolitical_security",
    "geoeconomic_trade",
    "supply_chain_logistics",
    "energy_commodities",
    "infrastructure_cyber_technology",
    "climate_environment_hazard",
  ],
  shipment_route_planning: [
    "geopolitical_security",
    "geoeconomic_trade",
    "supply_chain_logistics",
    "energy_commodities",
    "climate_environment_hazard",
  ],
  commodity_procurement: [
    "geopolitical_security",
    "geoeconomic_trade",
    "currency_capital_mobility",
    "supply_chain_logistics",
    "energy_commodities",
    "climate_environment_hazard",
  ],
  institutional_wallet_transfer: [
    "geopolitical_security",
    "geoeconomic_trade",
    "currency_capital_mobility",
    "banking_financial_system",
    "payments_treasury",
    "regulatory_legal",
  ],
  stablecoin_transfer: [
    "geopolitical_security",
    "geoeconomic_trade",
    "currency_capital_mobility",
    "payments_treasury",
    "regulatory_legal",
  ],
  stablecoin_redemption: [
    "currency_capital_mobility",
    "banking_financial_system",
    "payments_treasury",
    "regulatory_legal",
  ],
  autonomous_financial_agent_action: [
    "geopolitical_security",
    "geoeconomic_trade",
    "macro_monetary",
    "currency_capital_mobility",
    "banking_financial_system",
    "payments_treasury",
    "regulatory_legal",
    "emerging_long_tail",
  ],
};
