/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as OnchainRouteImport } from './routes/onchain'
import { Route as GlobalRiskRouteImport } from './routes/global-risk'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BridgeSwapRouteImport } from './routes/bridge-swap'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsGriArchitectureRouteImport } from './routes/docs_.gri-architecture'
import { Route as ApiRiskGateRouteImport } from './routes/api.risk-gate'

const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OnchainRoute = OnchainRouteImport.update({
  id: '/onchain',
  path: '/onchain',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRiskRoute = GlobalRiskRouteImport.update({
  id: '/global-risk',
  path: '/global-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeSwapRoute = BridgeSwapRouteImport.update({
  id: '/bridge-swap',
  path: '/bridge-swap',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGriArchitectureRoute = DocsGriArchitectureRouteImport.update({
  id: '/docs_/gri-architecture',
  path: '/docs/gri-architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRiskGateRoute = ApiRiskGateRouteImport.update({
  id: '/api/risk-gate',
  path: '/api/risk-gate',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/bridge': typeof BridgeRoute
  '/bridge-swap': typeof BridgeSwapRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/global-risk': typeof GlobalRiskRoute
  '/onchain': typeof OnchainRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/roadmap': typeof RoadmapRoute
  '/api/risk-gate': typeof ApiRiskGateRoute
  '/docs/gri-architecture': typeof DocsGriArchitectureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/bridge': typeof BridgeRoute
  '/bridge-swap': typeof BridgeSwapRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/global-risk': typeof GlobalRiskRoute
  '/onchain': typeof OnchainRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/roadmap': typeof RoadmapRoute
  '/api/risk-gate': typeof ApiRiskGateRoute
  '/docs/gri-architecture': typeof DocsGriArchitectureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/bridge': typeof BridgeRoute
  '/bridge-swap': typeof BridgeSwapRoute
  '/contact': typeof ContactRoute
  '/docs': typeof DocsRoute
  '/feed': typeof FeedRoute
  '/global-risk': typeof GlobalRiskRoute
  '/onchain': typeof OnchainRoute
  '/pipeline': typeof PipelineRoute
  '/portfolio': typeof PortfolioRoute
  '/roadmap': typeof RoadmapRoute
  '/api/risk-gate': typeof ApiRiskGateRoute
  '/docs_/gri-architecture': typeof DocsGriArchitectureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arena'
    | '/bridge'
    | '/bridge-swap'
    | '/contact'
    | '/docs'
    | '/feed'
    | '/global-risk'
    | '/onchain'
    | '/pipeline'
    | '/portfolio'
    | '/roadmap'
    | '/api/risk-gate'
    | '/docs/gri-architecture'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arena'
    | '/bridge'
    | '/bridge-swap'
    | '/contact'
    | '/docs'
    | '/feed'
    | '/global-risk'
    | '/onchain'
    | '/pipeline'
    | '/portfolio'
    | '/roadmap'
    | '/api/risk-gate'
    | '/docs/gri-architecture'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arena'
    | '/bridge'
    | '/bridge-swap'
    | '/contact'
    | '/docs'
    | '/feed'
    | '/global-risk'
    | '/onchain'
    | '/pipeline'
    | '/portfolio'
    | '/roadmap'
    | '/api/risk-gate'
    | '/docs_/gri-architecture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArenaRoute: typeof ArenaRoute
  BridgeRoute: typeof BridgeRoute
  BridgeSwapRoute: typeof BridgeSwapRoute
  ContactRoute: typeof ContactRoute
  DocsRoute: typeof DocsRoute
  FeedRoute: typeof FeedRoute
  GlobalRiskRoute: typeof GlobalRiskRoute
  OnchainRoute: typeof OnchainRoute
  PipelineRoute: typeof PipelineRoute
  PortfolioRoute: typeof PortfolioRoute
  RoadmapRoute: typeof RoadmapRoute
  ApiRiskGateRoute: typeof ApiRiskGateRoute
  DocsGriArchitectureRoute: typeof DocsGriArchitectureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onchain': {
      id: '/onchain'
      path: '/onchain'
      fullPath: '/onchain'
      preLoaderRoute: typeof OnchainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-risk': {
      id: '/global-risk'
      path: '/global-risk'
      fullPath: '/global-risk'
      preLoaderRoute: typeof GlobalRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge-swap': {
      id: '/bridge-swap'
      path: '/bridge-swap'
      fullPath: '/bridge-swap'
      preLoaderRoute: typeof BridgeSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs_/gri-architecture': {
      id: '/docs_/gri-architecture'
      path: '/docs/gri-architecture'
      fullPath: '/docs/gri-architecture'
      preLoaderRoute: typeof DocsGriArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/risk-gate': {
      id: '/api/risk-gate'
      path: '/api/risk-gate'
      fullPath: '/api/risk-gate'
      preLoaderRoute: typeof ApiRiskGateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArenaRoute: ArenaRoute,
  BridgeRoute: BridgeRoute,
  BridgeSwapRoute: BridgeSwapRoute,
  ContactRoute: ContactRoute,
  DocsRoute: DocsRoute,
  FeedRoute: FeedRoute,
  GlobalRiskRoute: GlobalRiskRoute,
  OnchainRoute: OnchainRoute,
  PipelineRoute: PipelineRoute,
  PortfolioRoute: PortfolioRoute,
  RoadmapRoute: RoadmapRoute,
  ApiRiskGateRoute: ApiRiskGateRoute,
  DocsGriArchitectureRoute: DocsGriArchitectureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
