-- =============================================================================
-- Geomacro Breaking-News Source Registry
--
-- Registers fast news/macro/minerals sources with conservative rights gates.
-- Registration is not equivalent to permission to republish full articles.
-- Hot-path collectors store only the minimum metadata needed for detection and
-- provenance; downstream customer output remains Geomacro-derived intelligence.
-- =============================================================================

insert into public.live_external_sources (
  source_id,
  source_name,
  provider_name,
  category,
  access_type,
  authentication_type,
  base_url,
  licence_name,
  commercial_usage_status,
  raw_redistribution_allowed,
  attribution_required,
  enabled_for_ingestion,
  enabled_for_commercial_signals,
  country_scope,
  freshness_class,
  notes
)
values
(
  'aljazeera_rss',
  'Al Jazeera RSS',
  'Al Jazeera Media Network',
  'GEOPOLITICS',
  'RSS',
  'NONE',
  'https://www.aljazeera.com/xml/rss/all.xml',
  null,
  'REVIEW_REQUIRED',
  false,
  true,
  true,
  false,
  'GLOBAL',
  'NEAR_REAL_TIME',
  'Fast headline discovery only. Store title/link/time and Geomacro-derived metadata; do not republish article bodies. Commercial signal use remains gated pending explicit rights review.'
),
(
  'federal_reserve_press_rss',
  'Federal Reserve Board Press Releases RSS',
  'Board of Governors of the Federal Reserve System',
  'MACRO',
  'RSS',
  'NONE',
  'https://www.federalreserve.gov/feeds/press_all.xml',
  null,
  'REVIEW_REQUIRED',
  false,
  true,
  true,
  false,
  'USA',
  'NEAR_REAL_TIME',
  'Official Federal Reserve press-release RSS. Store title/link/time and derived release classification. Keep commercial signal flag conservative until the exact downstream reuse policy is recorded.'
),
(
  'forexlive_rss',
  'ForexLive News RSS',
  'ForexLive',
  'MACRO',
  'RSS',
  'NONE',
  'https://www.forexlive.com/feed/news',
  null,
  'PERMISSION_REQUIRED',
  false,
  true,
  true,
  false,
  'GLOBAL',
  'REAL_TIME',
  'Internal breaking-macro detection only. ForexLive separately markets institutional RSS usage; do not expose or commercially redistribute feed content without permission.'
),
(
  'mining_com_rss',
  'MINING.com RSS',
  'MINING.com',
  'CRITICAL_MINERALS',
  'RSS',
  'NONE',
  'https://www.mining.com/feed/',
  null,
  'DERIVED_ONLY',
  false,
  true,
  true,
  false,
  'GLOBAL',
  'NEAR_REAL_TIME',
  'MINING.com publishes RSS syndication guidance that permits business feed use with links back to MINING.com. Geomacro still stores only minimal feed metadata and derived intelligence; no article-body redistribution.'
),
(
  'ap_news_rss_candidate',
  'AP News RSS Candidate',
  'The Associated Press',
  'GEOPOLITICS',
  'RSS',
  'NONE',
  'https://apnews.com/index.rss',
  null,
  'PERMISSION_REQUIRED',
  false,
  true,
  false,
  false,
  'GLOBAL',
  'NEAR_REAL_TIME',
  'Candidate only. Current automated fetch verification is unreliable/blocked and AP content rights are restrictive. Do not enable until AP provides a supported machine endpoint and usage rights for this deployment.'
),
(
  'reuters_world_candidate',
  'Reuters World Candidate',
  'Reuters',
  'GEOPOLITICS',
  'HTML',
  'NONE',
  'https://www.reuters.com/world/',
  null,
  'PERMISSION_REQUIRED',
  false,
  true,
  false,
  false,
  'GLOBAL',
  'REAL_TIME',
  'Do not scrape Reuters for the free-first production path. Detect Reuters-linked events through governed aggregators such as the existing GDELT layer unless a licensed Reuters feed is obtained.'
),
(
  'trading_economics_stream_candidate',
  'Trading Economics Live Stream Candidate',
  'Trading Economics',
  'MACRO',
  'API',
  'API_KEY',
  'https://api.tradingeconomics.com/',
  null,
  'PERMISSION_REQUIRED',
  false,
  true,
  false,
  false,
  'GLOBAL',
  'REAL_TIME',
  'Paid API/WebSocket source. Keep disabled in the free-first baseline. Enable only after a suitable subscription and redistribution/derived-output rights are approved.'
),
(
  'financialjuice_candidate',
  'FinancialJuice Candidate',
  'FinancialJuice',
  'MACRO',
  'HTML',
  'ACCOUNT',
  'https://www.financialjuice.com/home',
  null,
  'PERMISSION_REQUIRED',
  false,
  true,
  false,
  false,
  'GLOBAL',
  'REAL_TIME',
  'No supported free machine API/RSS has been approved for Geomacro. Do not scrape or automate the consumer site without explicit permission.'
),
(
  'forex_factory_calendar_candidate',
  'Forex Factory Calendar Candidate',
  'Forex Factory',
  'MACRO',
  'MIXED',
  'NONE',
  'https://www.forexfactory.com/calendar',
  null,
  'REVIEW_REQUIRED',
  false,
  true,
  false,
  false,
  'GLOBAL',
  'SOURCE_DEPENDENT',
  'Forex Factory exposes calendar export formats, but this is not treated as an unrestricted sub-minute production wire. Keep disabled until exact machine-use and reuse terms are recorded.'
),
(
  'world_news_api_candidate',
  'World News API Candidate',
  'World News API',
  'MULTI_DOMAIN',
  'API',
  'API_KEY',
  'https://worldnewsapi.com/',
  null,
  'PERMISSION_REQUIRED',
  false,
  true,
  false,
  false,
  'GLOBAL',
  'NEAR_REAL_TIME',
  'Free quota exists, but current terms restrict copying/storage including derived/hashed/transformed API data except narrow caching permissions. Not suitable for Geomacro permanent intelligence storage without written permission.'
),
(
  'newsapi_ai_candidate',
  'Event Registry / NewsAPI.ai Candidate',
  'Event Registry',
  'MULTI_DOMAIN',
  'API',
  'API_KEY',
  'https://newsapi.ai/',
  null,
  'REVIEW_REQUIRED',
  false,
  true,
  false,
  false,
  'GLOBAL',
  'NEAR_REAL_TIME',
  'Useful optional enrichment source. Free account credits are finite; production/commercial use should be enabled only after plan economics and publisher-rights handling are approved.'
)
on conflict (source_id)
do update set
  source_name = excluded.source_name,
  provider_name = excluded.provider_name,
  category = excluded.category,
  access_type = excluded.access_type,
  authentication_type = excluded.authentication_type,
  base_url = excluded.base_url,
  licence_name = excluded.licence_name,
  commercial_usage_status = excluded.commercial_usage_status,
  raw_redistribution_allowed = excluded.raw_redistribution_allowed,
  attribution_required = excluded.attribution_required,
  enabled_for_ingestion = excluded.enabled_for_ingestion,
  enabled_for_commercial_signals = excluded.enabled_for_commercial_signals,
  country_scope = excluded.country_scope,
  freshness_class = excluded.freshness_class,
  notes = excluded.notes,
  updated_at = now();
