-- Production-history marker only.
-- The original legacy RLS role scoping was applied directly to production at this timestamp.
-- Clean replay defers the same behavior-preserving policy scope change until migration 9984.
