-- Production-history marker only.
-- The original safe performance cleanup was applied directly to production at this timestamp.
-- Clean replay defers the same idempotent operations until migration 9982,
-- after commercial/testnet tables and policies exist.
