-- Production-history marker only.
-- The original hardening was applied directly to production at this timestamp.
-- Clean replay defers the same idempotent hardening until migration 9981,
-- after the dependent raw/realtime tables and maintenance functions exist.
