-- Compatibility placeholder retained because this migration version may already
-- exist in remote migration history.
--
-- Fresh local replays sort this timestamped migration before the later 9xx
-- source-certification schema series. The original body referenced
-- public.live_source_certification_evidence_runs before 961 creates it, so a
-- zero-database replay failed before reaching the canonical schema migration.
--
-- The original idempotent archive table/function DDL now lives in
-- 973_source_cert_evidence_b2_archive_cleanup.sql, after the source evidence
-- graph exists. Do not add schema dependencies here.
