-- Production-history marker only.
-- The original hot-path FK indexes were applied directly to production at this timestamp.
-- Clean replay defers the same idempotent index creation until migration 9983,
-- after all referenced tables exist.
