-- =============================================================================
-- Geomacro private commercial revenue delivery ledger
--
-- PURPOSE
-- - preserve one detailed, private, immutable proof row for every reconciled
--   real commercial earning
-- - bind payment -> settlement -> exact delivered intelligence -> usage evidence
-- - make the ledger append-only and tamper-evident with a SHA-256 hash chain
-- - keep internal canaries/testnet/sandbox activity out of the revenue ledger
--
-- PRIVATE BOUNDARY
-- - service-role read access only; no public/anon/authenticated access
-- - never stores raw payment signatures/tokens, private keys, API credentials,
--   auth headers, facilitator secrets or wallet private material
-- - payer identity remains hashed; the exact buyer-visible response is preserved
--   privately because it is the core proof of what Geomacro delivered
-- =============================================================================

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.private_commercial_revenue_delivery_ledger (
  id uuid primary key default gen_random_uuid(),
  sequence_no bigint generated by default as identity unique,
  recorded_at timestamptz not null default now(),

  payment_event_id uuid not null unique
    references public.commercial_payment_events(id) on delete restrict,
  usage_event_id uuid
    references public.commercial_usage_events(id) on delete restrict,

  payment_occurred_at timestamptz not null,
  settled_at timestamptz not null,
  delivered_at timestamptz not null,
  reconciled_at timestamptz not null,

  environment text not null,
  provider text not null,
  provider_environment text,
  purchase_classification text not null,
  payment_method text not null,

  principal_id uuid,
  entitlement_grant_id uuid,
  offer_id text,
  tier text,

  network_family text not null,
  network_name text,
  chain_id text,
  settlement_network text,

  asset_symbol text,
  asset_contract text,
  amount_atomic numeric(78,0),
  amount_decimal numeric(38,18),
  settlement_currency text,
  settlement_amount numeric(38,8),
  fee_currency text,
  provider_fee_amount numeric(38,8),
  geomacro_fee_amount numeric(38,8),

  provider_order_id text,
  provider_payment_id text,
  provider_settlement_id text not null,
  settlement_reference_sha256 text not null,
  tx_hash text,
  block_number numeric(30,0),
  confirmations integer,

  payer_reference_hash text,
  recipient_reference_hash text,

  delivery_ledger text not null,
  delivery_record_id uuid not null,
  payment_fingerprint_sha256 text,
  request_fingerprint_sha256 text,
  request_id text not null,
  client_request_id text,
  product_id text not null,
  capability text not null,
  subject_type text,
  subject_key text,

  query_plan_hash text,
  delivered_product_hash text not null,
  response_sha256 text not null,
  delivery_snapshot_sha256 text not null,

  risk_object_id text,
  risk_object_version text,
  risk_object_signed boolean not null default false,
  risk_gate_included boolean not null default false,
  risk_gate_decision text,
  idempotent_replay boolean not null default false,
  execution_authorized boolean not null default false,

  reconciliation_reference text not null,
  revenue_classification text not null,
  commercial_revenue boolean not null,

  -- Exact buyer-visible delivered response. This is deliberately private and is
  -- never exposed by public proof/dashboard surfaces.
  private_delivery_snapshot jsonb not null,

  -- Canonical internal proof envelope used to compute the tamper-evident chain.
  proof_document jsonb not null,
  previous_entry_sha256 text,
  entry_sha256 text not null unique,

  constraint private_revenue_environment_check
    check (environment in ('mainnet','fiat')),
  constraint private_revenue_purchase_classification_check
    check (purchase_classification in ('external_customer','independent_production_buyer')),
  constraint private_revenue_delivery_ledger_check
    check (delivery_ledger in ('coinbase_x402_deliveries','agent_commerce_deliveries')),
  constraint private_revenue_settlement_hash_check
    check (settlement_reference_sha256 ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_payment_hash_check
    check (payment_fingerprint_sha256 is null or payment_fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_request_hash_check
    check (request_fingerprint_sha256 is null or request_fingerprint_sha256 ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_query_plan_hash_check
    check (query_plan_hash is null or query_plan_hash ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_product_hash_check
    check (delivered_product_hash ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_response_hash_check
    check (response_sha256 ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_snapshot_hash_check
    check (delivery_snapshot_sha256 ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_previous_hash_check
    check (previous_entry_sha256 is null or previous_entry_sha256 ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_entry_hash_check
    check (entry_sha256 ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_payer_hash_check
    check (payer_reference_hash is null or payer_reference_hash ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_recipient_hash_check
    check (recipient_reference_hash is null or recipient_reference_hash ~ '^[0-9a-f]{64}$'),
  constraint private_revenue_reconciliation_check
    check (revenue_classification = 'commercial_revenue' and commercial_revenue = true),
  constraint private_revenue_execution_boundary_check
    check (execution_authorized = false),
  constraint private_revenue_amount_check
    check (amount_atomic is null or amount_atomic > 0),
  constraint private_revenue_request_id_check
    check (char_length(request_id) between 8 and 160),
  constraint private_revenue_product_id_check
    check (char_length(product_id) between 3 and 128),
  constraint private_revenue_capability_check
    check (char_length(capability) between 2 and 80)
);

create index if not exists private_revenue_delivery_recorded_idx
  on public.private_commercial_revenue_delivery_ledger (recorded_at desc);
create index if not exists private_revenue_delivery_provider_idx
  on public.private_commercial_revenue_delivery_ledger (provider, settled_at desc);
create index if not exists private_revenue_delivery_request_idx
  on public.private_commercial_revenue_delivery_ledger (request_id);
create index if not exists private_revenue_delivery_product_idx
  on public.private_commercial_revenue_delivery_ledger (product_id, delivered_at desc);
create index if not exists private_revenue_delivery_settlement_hash_idx
  on public.private_commercial_revenue_delivery_ledger (settlement_reference_sha256);

alter table public.private_commercial_revenue_delivery_ledger enable row level security;

revoke all on table public.private_commercial_revenue_delivery_ledger
  from PUBLIC, anon, authenticated, service_role;
grant select on table public.private_commercial_revenue_delivery_ledger
  to service_role;

-- Append-only means even service-role application code cannot silently rewrite
-- or delete proof. Database-owner break-glass administration remains outside the
-- application contract.
create or replace function public.guard_private_commercial_revenue_delivery_ledger()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  raise exception 'private commercial revenue delivery ledger is append-only';
end;
$$;

revoke all on function public.guard_private_commercial_revenue_delivery_ledger()
  from PUBLIC, anon, authenticated, service_role;

drop trigger if exists private_commercial_revenue_delivery_ledger_immutable
  on public.private_commercial_revenue_delivery_ledger;
create trigger private_commercial_revenue_delivery_ledger_immutable
before update or delete on public.private_commercial_revenue_delivery_ledger
for each row
execute function public.guard_private_commercial_revenue_delivery_ledger();

create or replace function public.capture_private_commercial_revenue_delivery_proof()
returns trigger
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_delivery_ledger text;
  v_delivery_id uuid;
  v_payment_fingerprint text;
  v_request_fingerprint text;
  v_client_request_id text;
  v_product_id text;
  v_delivery_response jsonb;
  v_response_sha256 text;
  v_settlement_reference text;
  v_settlement_network text;
  v_delivery_amount numeric(78,0);
  v_delivery_payer_hash text;
  v_delivery_recipient_hash text;
  v_delivered_at timestamptz;
  v_delivery_settled_at timestamptz;

  v_usage public.commercial_usage_events%rowtype;

  v_purchase_classification text;
  v_query_plan_hash text;
  v_delivered_product_hash text;
  v_snapshot_sha256 text;
  v_settlement_sha256 text;
  v_previous_entry_sha256 text;
  v_entry_sha256 text;
  v_reconciled_at timestamptz;
  v_proof_document jsonb;
begin
  -- This trigger is attached to payment events. Ignore all non-revenue states.
  if new.commercial_revenue is not true then
    return new;
  end if;

  -- If an existing row is updated for an unrelated field after revenue was
  -- already captured, do not create a duplicate. payment_event_id is unique too.
  if exists (
    select 1
    from public.private_commercial_revenue_delivery_ledger l
    where l.payment_event_id = new.id
  ) then
    return new;
  end if;

  if new.environment not in ('mainnet','fiat')
     or new.payment_status <> 'settled'
     or new.reconciliation_status <> 'matched'
     or new.revenue_classification <> 'commercial_revenue' then
    raise exception 'commercial revenue proof capture requires settled matched production revenue';
  end if;

  v_purchase_classification := coalesce(new.metadata ->> 'purchase_classification', '');
  if v_purchase_classification not in ('external_customer','independent_production_buyer') then
    raise exception 'private revenue proof requires external/independent buyer classification';
  end if;

  if coalesce(new.metadata ->> 'internal_canary', 'false')::boolean is true then
    raise exception 'internal canary cannot enter private commercial revenue delivery ledger';
  end if;

  if trim(coalesce(new.provider_settlement_id, '')) = '' then
    raise exception 'commercial revenue proof requires provider settlement reference';
  end if;

  -- Load the exact durable delivery row that produced this revenue.
  if new.provider = 'coinbase_cdp_x402' then
    select
      'coinbase_x402_deliveries',
      d.id,
      d.payment_fingerprint_sha256,
      d.request_fingerprint_sha256,
      d.client_request_id,
      coalesce(d.response_payload ->> 'product', 'geomacro_adaptive_risk_intelligence_v1'),
      d.response_payload,
      d.response_sha256,
      d.settlement_tx,
      d.settlement_network,
      d.amount_atomic,
      d.payer_reference_hash,
      d.pay_to_hash,
      d.delivered_at,
      d.settled_at
    into
      v_delivery_ledger,
      v_delivery_id,
      v_payment_fingerprint,
      v_request_fingerprint,
      v_client_request_id,
      v_product_id,
      v_delivery_response,
      v_response_sha256,
      v_settlement_reference,
      v_settlement_network,
      v_delivery_amount,
      v_delivery_payer_hash,
      v_delivery_recipient_hash,
      v_delivered_at,
      v_delivery_settled_at
    from public.coinbase_x402_deliveries d
    where d.environment = 'mainnet'
      and d.state = 'delivered'
      and d.settlement_tx = new.provider_settlement_id
    order by d.updated_at desc
    limit 1;
  elsif new.provider in ('circle_gateway_x402','nevermined_x402') then
    select
      'agent_commerce_deliveries',
      d.id,
      d.payment_fingerprint_sha256,
      d.request_fingerprint_sha256,
      d.client_request_id,
      d.product_id,
      d.response_payload,
      d.response_sha256,
      d.settlement_reference,
      d.settlement_network,
      d.amount_atomic,
      d.payer_reference_hash,
      d.recipient_reference_hash,
      d.delivered_at,
      d.settled_at
    into
      v_delivery_ledger,
      v_delivery_id,
      v_payment_fingerprint,
      v_request_fingerprint,
      v_client_request_id,
      v_product_id,
      v_delivery_response,
      v_response_sha256,
      v_settlement_reference,
      v_settlement_network,
      v_delivery_amount,
      v_delivery_payer_hash,
      v_delivery_recipient_hash,
      v_delivered_at,
      v_delivery_settled_at
    from public.agent_commerce_deliveries d
    where d.provider = case
      when new.provider = 'circle_gateway_x402' then 'circle_gateway_x402'
      else 'nevermined'
    end
      and d.provider_environment = new.provider_environment
      and d.state = 'delivered'
      and d.settlement_reference = new.provider_settlement_id
    order by d.updated_at desc
    limit 1;
  else
    raise exception 'unsupported provider for private commercial revenue proof: %', new.provider;
  end if;

  if v_delivery_id is null
     or v_delivery_response is null
     or v_response_sha256 !~ '^[0-9a-f]{64}$'
     or v_delivery_settled_at is null
     or v_delivered_at is null then
    raise exception 'commercial revenue proof cannot locate complete durable delivery evidence';
  end if;

  if trim(coalesce(v_settlement_reference, '')) <> trim(new.provider_settlement_id) then
    raise exception 'private revenue proof settlement reference mismatch';
  end if;

  if new.provider_payment_id is not null
     and v_payment_fingerprint is not null
     and new.provider_payment_id <> v_payment_fingerprint then
    raise exception 'private revenue proof payment fingerprint mismatch';
  end if;

  if new.amount_atomic is not null
     and v_delivery_amount is not null
     and new.amount_atomic <> v_delivery_amount then
    raise exception 'private revenue proof amount mismatch';
  end if;

  if new.payer_reference_hash is not null
     and v_delivery_payer_hash is not null
     and new.payer_reference_hash <> v_delivery_payer_hash then
    raise exception 'private revenue proof payer mismatch';
  end if;

  if new.recipient_reference_hash is not null
     and v_delivery_recipient_hash is not null
     and new.recipient_reference_hash <> v_delivery_recipient_hash then
    raise exception 'private revenue proof recipient mismatch';
  end if;

  if coalesce((v_delivery_response ->> 'execution_authorized')::boolean, false) is distinct from false then
    raise exception 'private revenue proof execution boundary violation';
  end if;

  v_delivered_product_hash := lower(coalesce(v_delivery_response ->> 'delivered_product_hash', ''));
  if v_delivered_product_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'private revenue proof is missing delivered product hash';
  end if;

  if lower(coalesce(new.metadata ->> 'reconciled_delivered_product_hash', '')) <> v_delivered_product_hash then
    raise exception 'private revenue proof delivered product hash differs from reconciliation evidence';
  end if;

  v_query_plan_hash := lower(nullif(v_delivery_response ->> 'query_plan_hash', ''));
  if v_query_plan_hash is not null and v_query_plan_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'private revenue proof query plan hash is invalid';
  end if;

  select u.*
    into v_usage
  from public.commercial_usage_events u
  where u.payment_event_id = new.id
    and u.environment = new.environment
    and u.access_surface = 'agent_payment'
    and u.success is true
    and u.execution_authorized is false
    and u.response_sha256 = v_response_sha256
  order by u.idempotent_replay asc, u.occurred_at asc
  limit 1;

  if not found then
    raise exception 'private revenue proof requires matching successful usage evidence';
  end if;

  v_settlement_sha256 := encode(
    extensions.digest(convert_to(lower(trim(new.provider_settlement_id)), 'UTF8'), 'sha256'),
    'hex'
  );
  v_snapshot_sha256 := encode(
    extensions.digest(convert_to(v_delivery_response::text, 'UTF8'), 'sha256'),
    'hex'
  );
  v_reconciled_at := coalesce(
    nullif(new.metadata ->> 'reconciled_at', '')::timestamptz,
    now()
  );

  v_proof_document := jsonb_build_object(
    'schema_version', 'geomacro.private-commercial-revenue-delivery-proof.v1',
    'payment_event_id', new.id,
    'usage_event_id', v_usage.id,
    'payment_occurred_at', new.occurred_at,
    'settled_at', new.settled_at,
    'delivered_at', v_delivered_at,
    'reconciled_at', v_reconciled_at,
    'environment', new.environment,
    'provider', new.provider,
    'provider_environment', new.provider_environment,
    'purchase_classification', v_purchase_classification,
    'payment_method', new.payment_method,
    'principal_id', new.principal_id,
    'entitlement_grant_id', new.entitlement_grant_id,
    'offer_id', new.offer_id,
    'tier', new.tier,
    'network_family', new.network_family,
    'network_name', new.network_name,
    'chain_id', new.chain_id,
    'settlement_network', v_settlement_network,
    'asset_symbol', new.asset_symbol,
    'asset_contract', new.asset_contract,
    'amount_atomic', new.amount_atomic,
    'amount_decimal', new.amount_decimal,
    'settlement_currency', new.settlement_currency,
    'settlement_amount', new.settlement_amount,
    'fee_currency', new.fee_currency,
    'provider_fee_amount', new.provider_fee_amount,
    'geomacro_fee_amount', new.geomacro_fee_amount,
    'provider_order_id', new.provider_order_id,
    'provider_payment_id', new.provider_payment_id,
    'provider_settlement_id', new.provider_settlement_id,
    'settlement_reference_sha256', v_settlement_sha256,
    'tx_hash', new.tx_hash,
    'block_number', new.block_number,
    'confirmations', new.confirmations,
    'payer_reference_hash', new.payer_reference_hash,
    'recipient_reference_hash', new.recipient_reference_hash,
    'delivery_ledger', v_delivery_ledger,
    'delivery_record_id', v_delivery_id,
    'payment_fingerprint_sha256', v_payment_fingerprint,
    'request_fingerprint_sha256', v_request_fingerprint,
    'request_id', v_usage.request_id,
    'client_request_id', v_client_request_id,
    'product_id', v_product_id,
    'capability', v_usage.capability,
    'subject_type', v_usage.subject_type,
    'subject_key', v_usage.subject_key,
    'query_plan_hash', v_query_plan_hash,
    'delivered_product_hash', v_delivered_product_hash,
    'response_sha256', v_response_sha256,
    'delivery_snapshot_sha256', v_snapshot_sha256,
    'risk_object_id', v_usage.risk_object_id,
    'risk_object_version', v_usage.risk_object_version,
    'risk_object_signed', v_usage.risk_object_signed,
    'risk_gate_included', v_usage.risk_gate_included,
    'risk_gate_decision', v_usage.risk_gate_decision,
    'idempotent_replay', v_usage.idempotent_replay,
    'execution_authorized', false,
    'reconciliation_reference', new.reconciliation_reference,
    'revenue_classification', new.revenue_classification,
    'commercial_revenue', true,
    'delivery_snapshot', v_delivery_response,
    'secrets_included', false,
    'raw_payment_signature_included', false,
    'private_key_included', false
  );

  -- Serialize only the proof-chain append, not the provider/payment path itself.
  perform pg_advisory_xact_lock(hashtext('geomacro_private_commercial_revenue_delivery_ledger_v1'));

  select l.entry_sha256
    into v_previous_entry_sha256
  from public.private_commercial_revenue_delivery_ledger l
  order by l.sequence_no desc
  limit 1;

  v_entry_sha256 := encode(
    extensions.digest(
      convert_to(
        coalesce(v_previous_entry_sha256, 'GENESIS') || '|' || v_proof_document::text,
        'UTF8'
      ),
      'sha256'
    ),
    'hex'
  );

  insert into public.private_commercial_revenue_delivery_ledger (
    payment_event_id,
    usage_event_id,
    payment_occurred_at,
    settled_at,
    delivered_at,
    reconciled_at,
    environment,
    provider,
    provider_environment,
    purchase_classification,
    payment_method,
    principal_id,
    entitlement_grant_id,
    offer_id,
    tier,
    network_family,
    network_name,
    chain_id,
    settlement_network,
    asset_symbol,
    asset_contract,
    amount_atomic,
    amount_decimal,
    settlement_currency,
    settlement_amount,
    fee_currency,
    provider_fee_amount,
    geomacro_fee_amount,
    provider_order_id,
    provider_payment_id,
    provider_settlement_id,
    settlement_reference_sha256,
    tx_hash,
    block_number,
    confirmations,
    payer_reference_hash,
    recipient_reference_hash,
    delivery_ledger,
    delivery_record_id,
    payment_fingerprint_sha256,
    request_fingerprint_sha256,
    request_id,
    client_request_id,
    product_id,
    capability,
    subject_type,
    subject_key,
    query_plan_hash,
    delivered_product_hash,
    response_sha256,
    delivery_snapshot_sha256,
    risk_object_id,
    risk_object_version,
    risk_object_signed,
    risk_gate_included,
    risk_gate_decision,
    idempotent_replay,
    execution_authorized,
    reconciliation_reference,
    revenue_classification,
    commercial_revenue,
    private_delivery_snapshot,
    proof_document,
    previous_entry_sha256,
    entry_sha256
  ) values (
    new.id,
    v_usage.id,
    new.occurred_at,
    coalesce(new.settled_at, v_delivery_settled_at),
    v_delivered_at,
    v_reconciled_at,
    new.environment,
    new.provider,
    new.provider_environment,
    v_purchase_classification,
    new.payment_method,
    new.principal_id,
    new.entitlement_grant_id,
    new.offer_id,
    new.tier,
    new.network_family,
    new.network_name,
    new.chain_id,
    v_settlement_network,
    new.asset_symbol,
    new.asset_contract,
    new.amount_atomic,
    new.amount_decimal,
    new.settlement_currency,
    new.settlement_amount,
    new.fee_currency,
    new.provider_fee_amount,
    new.geomacro_fee_amount,
    new.provider_order_id,
    new.provider_payment_id,
    new.provider_settlement_id,
    v_settlement_sha256,
    new.tx_hash,
    new.block_number,
    new.confirmations,
    new.payer_reference_hash,
    new.recipient_reference_hash,
    v_delivery_ledger,
    v_delivery_id,
    v_payment_fingerprint,
    v_request_fingerprint,
    v_usage.request_id,
    v_client_request_id,
    v_product_id,
    v_usage.capability,
    v_usage.subject_type,
    v_usage.subject_key,
    v_query_plan_hash,
    v_delivered_product_hash,
    v_response_sha256,
    v_snapshot_sha256,
    v_usage.risk_object_id,
    v_usage.risk_object_version,
    v_usage.risk_object_signed,
    v_usage.risk_gate_included,
    v_usage.risk_gate_decision,
    v_usage.idempotent_replay,
    false,
    new.reconciliation_reference,
    new.revenue_classification,
    true,
    v_delivery_response,
    v_proof_document,
    v_previous_entry_sha256,
    v_entry_sha256
  );

  return new;
end;
$$;

revoke all on function public.capture_private_commercial_revenue_delivery_proof()
  from PUBLIC, anon, authenticated, service_role;

drop trigger if exists capture_private_commercial_revenue_delivery_proof
  on public.commercial_payment_events;
create trigger capture_private_commercial_revenue_delivery_proof
after insert or update of commercial_revenue,reconciliation_status,revenue_classification,metadata
on public.commercial_payment_events
for each row
when (new.commercial_revenue is true)
execute function public.capture_private_commercial_revenue_delivery_proof();

-- Independent verifier: recompute every entry hash and every previous-link from
-- stored proof documents. It does not mutate the ledger.
create or replace function public.verify_private_commercial_revenue_delivery_ledger()
returns table (
  sequence_no bigint,
  payment_event_id uuid,
  stored_previous_entry_sha256 text,
  expected_previous_entry_sha256 text,
  stored_entry_sha256 text,
  recomputed_entry_sha256 text,
  previous_link_valid boolean,
  entry_hash_valid boolean
)
language sql
security definer
set search_path = public, extensions
as $$
  with ordered as (
    select
      l.sequence_no,
      l.payment_event_id,
      l.previous_entry_sha256,
      l.entry_sha256,
      l.proof_document,
      lag(l.entry_sha256) over (order by l.sequence_no) as expected_previous
    from public.private_commercial_revenue_delivery_ledger l
  )
  select
    o.sequence_no,
    o.payment_event_id,
    o.previous_entry_sha256,
    o.expected_previous,
    o.entry_sha256,
    encode(
      extensions.digest(
        convert_to(
          coalesce(o.expected_previous, 'GENESIS') || '|' || o.proof_document::text,
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    ) as recomputed_entry_sha256,
    o.previous_entry_sha256 is not distinct from o.expected_previous as previous_link_valid,
    o.entry_sha256 = encode(
      extensions.digest(
        convert_to(
          coalesce(o.expected_previous, 'GENESIS') || '|' || o.proof_document::text,
          'UTF8'
        ),
        'sha256'
      ),
      'hex'
    ) as entry_hash_valid
  from ordered o
  order by o.sequence_no;
$$;

revoke all on function public.verify_private_commercial_revenue_delivery_ledger()
  from PUBLIC, anon, authenticated;
grant execute on function public.verify_private_commercial_revenue_delivery_ledger()
  to service_role;

comment on table public.private_commercial_revenue_delivery_ledger is
  'Geomacro-private append-only proof ledger for every reconciled real commercial earning. Captures exact buyer-visible delivery, settlement/accounting evidence and a SHA-256 hash chain. Never public.';
comment on function public.verify_private_commercial_revenue_delivery_ledger() is
  'Read-only internal verifier that recomputes the private revenue delivery ledger hash chain. Service-role only.';
